### ISSUE TITLE
annot use c (type *"github.com/caddyserver/caddy".Controller) as type *"github.com/coredns/caddy".Controller in argument to dnsserver.GetConfig

### ISSUE THREAD

**Issue by firstdorsal** [arvancloud/redis#20]
go get throws this error
../../../go/pkg/mod/github.com/hawell/redis@v0.0.0-20190818082518-8a6e3c44c0ac/setup.go:24:21: cannot use c (type *"github.com/caddyserver/caddy".Controller) as type *"github.com/coredns/caddy".Controller in argument to dnsserver.GetConfig

**Comment by bacchus101** [comment]
I'm getting the exact same error. Did you ever figure out a solution?

**Comment by firstdorsal** [comment]
nope. we are building our own dns server now xD

**Comment by chrisohaver** [comment]
See #18
